---
driver:
  name: docker
  use_sudo: false
  provision_command: sed -i '/tsflags=nodocs/d' /etc/yum.conf

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true

platforms:
  - name: centos-7.2
    driver_config:
      image: williamyeh/ansible:centos7
      platform: centos

verifier:
  name: inspec

suites:
  - name: default
