---

- name: install golang package
  package:
    name: "{{ item }}"
  become: true
  with_items:
    - golang
    - git

- name: create golang home
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ go_path }}'
    - '{{ go_path }}/bin'
    - '{{ go_path }}/pkg'
    - '{{ go_path }}/src'

- name: add GOPATH to user's environment if missing
  lineinfile:
    path: "{{ lookup('env','HOME') }}/.profile"
    regexp: '^GOPATH='
    line: "GOPATH={{ go_path}}"
    state: present
    create: true

- name: install common go dependencies
  command: 'go get -u {{ item.url }}'
  environment:
    GOPATH: '{{ GOPATH }}'
    GOROOT: '{{ GOROOT }}'
  with_items: '{{ go_deps }}'
  changed_when: false
