---

- name: install golang package
  package:
    name: golang
    state: latest
  become: true

- name: create golang home
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ go_path }}'
    - '{{ go_path }}/bin'
    - '{{ go_path }}/pkg'
    - '{{ go_path }}/src'

- lineinfile:
    path: "{{ lookup('env','HOME') }}/.profile"
    regexp: '^GOPATH='
    line: "GOPATH={{ go_path}}"

- name: install common go dependencies
  shell: 'go get -u {{ item.url }}'
  environment:
    GOPATH: '{{ GOPATH }}'
    GOROOT: '{{ GOROOT }}'
  with_items: '{{ go_deps }}'
  changed_when: false
