---

- name: Enable Neovim repo for Ubuntu
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Enable Neovim repo for CentOS/RHEL
  yum_repository:
    name:
    baseurl: "{{ nvim_repo_url }}"
    gpgkey:  "{{ nvim_repo_gpg }}"
    gpgcheck: yes
    skip_if_unavailable: yes
    state: present
  become: yes
  when: ansible_distribution == 'RedHat'

- name: Install EPEL for Neovim on CentOS/RHEL
  package:
    name: epel-release
    state: present
  become: yes
  when: ansible_distribution == 'RedHat'

- name: Install vim and neovim packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - neovim
  become: yes

- name: Create directories for vim-plug
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ dev_user }}"
    mode: 0775
  with_items:
    - "{{ vim_plug_dir }}"
    - "{{ nvim_plug_dir }}"

- name: Download vim-plug
  get_url:
    url: "{{ vim_plug_url }}"
    dest: "{{ item }}"
    mode: 0775
  with_items:
    - "{{ vim_plug_dest }}"
    - "{{ nvim_plug_dest }}"

- name: Create .vimrc config
  template:
    src: vimrc.j2
    dest: "{{ vimrc_dest }}"
    owner: "{{ dev_user }}"
    mode: 0775
    backup: yes
  when: vimrc_ansible_managed

- name: Ensure Neovim config directory is present
  file:
    path: "{{ nvimrc_dir }}"
    state: directory
    owner: "{{ dev_user }}"
    mode: 0775

- name: Symlink Vim and Neovim config
  file:
    src: "{{ vimrc_dest }}"
    dest: "{{ nvimrc_dest }}"
    state: link

# This would be a nice to have, but isn't completely necessary
# - name: Install Vim and Neovim plugins
#   shell: "{{ item }} -Esc source {{ vimrc_dest }} -c PlugInstall -c qa"
#   with_items:
#     - vim
#     - nvim
#   when: vim_install_plugins
