---

- name: add vscode repo
  yum_repository:
    file: vscode
    name: code
    description: Visual Studio Code
    baseurl: '{{ vscode_repo_url }}'
    gpgkey: '{{ vscode_repo_key }}'
    gpgcheck: yes
  become: true

- name: install vscode package
  package:
    name: code
    state: latest
  become: true

- name: install vscode extensions
  shell: 'code --install-extension -u {{ item.name }}'
  with_items: '{{ vscode_extensions }}'
  changed_when: false
